name: Notify Discord on Merge to Integration

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read
  id-token: write

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          ACTOR="${{ github.event.pusher.name }}"
          PR_TITLE="${{ github.event.commits.message }}"

          ESCAPED_PR_TITLE=$(echo "$PR_TITLE" | sed 's/"/\\"/g')

          echo "{\"content\": \"✅ {## Attention \n\nPush to the repo \`main\`has been closed by \`${ACTOR}\`.\n\"}" > payload.json

          cat payload.json

          curl -X POST "$DISCORD_WEBHOOK" \
               -H "Content-Type: application/json" \
               -d @payload.json