name: Notify Discord on Merge to Integration

on:
  pull_request_target:
    types: [closed]
    branches:
      - main

permissions:
  contents: read
  pull-requests: read
  id-token: write

jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          ACTOR="${{ github.actor }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"

          ESCAPED_PR_TITLE=$(echo "$PR_TITLE" | sed 's/"/\\"/g')

          echo "{\"content\": \"✅ Pull Request ke \`integration\` telah di-merge oleh \`${ACTOR}\`.\n📌 Judul: \\\"${ESCAPED_PR_TITLE}\\\"\n🔗 ${PR_URL}\"}" > payload.json

          cat payload.json

          curl -X POST "$DISCORD_WEBHOOK" \
               -H "Content-Type: application/json" \
               -d @payload.json